### ISSUE TITLE
Import from Wordpress

### ISSUE THREAD

**Issue by zezaku** [pageer/lnblog#25]
Hello.
I will like to know if u plain to add wordpress support for fully converting from wordpress to LnBlog?
Thank you.

**Comment by pageer** [comment]
Sounds like a good idea to me.  I was already planning an export feature.  Adding an import feature to go with it makes a lot of sense.  If nothing else, it would make it easier for people to adopt LnBlog.  Consider it added to the "features to implement" list.

**Comment by zezaku** [comment]
Thank you 🧑🏻.Ill switch from wordpress when is done.

**Comment by pageer** [comment]
The initial requirements and design for this feature are documented here: 
https://1drv.ms/w/s!AkHV6W6P_AgNgtMvESEBPevbROG64g?e=hU6jfn

The main limitation for the initial version will be media items and post content.  LnBlog does not have a concept of a "media library" in the way that Wordpress does (the closest thing would be just copying the raw files), so we're not going to attempt to import media items for now.  Likewise, we're not going to try to copy any fancy rendering or styling stuff that Wordpress might do, so we'll just import the HTML from the export file as-is.  Assuming the original media files are left in place, this should "just work".

A media import and mass-post-update feature might be a useful future improvement, but is beyond the scope of this ticket.
